export default {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  CREATE_ALBUM: "CREATE_ALBUM",
  GET_ALBUM: "GET_ALBUM",
  GET_ALBUMS: "GET_ALBUMS",
  DELETE_ALBUM: "DELETE_ALBUM",
  EDIT_ALBUM: "EDIT_ALBUM",
};
